Option Strict Off
Option Explicit On
Module CARcode
	' JBCSTART Program
	'   Generate best quess initial parameters for the tcisoc.car file
	'
	'   J. Ball    4-April-2007       Date of latest revision: 6/24/07
	'
	Public C(20) As Object
	Public Pbuf, CaseID, Pval, filNam As Object
	Public SR As String
	Public Tflag, Pflag, Eflag, Rflag, CCflag As Object
	Public PartID As Short
	Public IDflag As Object
    Public Xflag As Short
    ' E needs to be explicitly a Decimal rather than an Object.  EjP 20230711
    'Public dL, E, partA, PartM, partZ, R, rf As Object
    Public dL, partA, PartM, partZ, R, rf As Object
    Public E As Decimal

    Public Rad(9) As Object
	Public KB As Single
	
	'UPGRADE_NOTE: Main was upgraded to Main_Renamed. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="A9E4979A-37FA-4718-9994-97DD76ED70A7"'
	Public Sub Main_Renamed()
		'UPGRADE_WARNING: Couldn't resolve default property of object Eflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Eflag = 0
		'UPGRADE_WARNING: Couldn't resolve default property of object Pflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pflag = 0
		'UPGRADE_WARNING: Couldn't resolve default property of object Rflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rflag = 0
		'UPGRADE_WARNING: Couldn't resolve default property of object CCflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		CCflag = 0
		'UPGRADE_WARNING: Couldn't resolve default property of object dL. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		dL = 1# 'orbit stretch factor (actual path/pi*R^2)
		'
		'UPGRADE_WARNING: Couldn't resolve default property of object Rad(0). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rad(0) = 29#
		'UPGRADE_WARNING: Couldn't resolve default property of object Rad(1). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rad(1) = 29.5
		'UPGRADE_WARNING: Couldn't resolve default property of object Rad(2). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rad(2) = 30#
		'UPGRADE_WARNING: Couldn't resolve default property of object Rad(3). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rad(3) = 30.5
		'UPGRADE_WARNING: Couldn't resolve default property of object Rad(4). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rad(4) = 31#
		'UPGRADE_WARNING: Couldn't resolve default property of object Rad(5). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rad(5) = 31.1
		'UPGRADE_WARNING: Couldn't resolve default property of object Rad(6). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rad(6) = 31.2
		'UPGRADE_WARNING: Couldn't resolve default property of object Rad(7). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rad(7) = 31.3
		'UPGRADE_WARNING: Couldn't resolve default property of object Rad(8). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rad(8) = 31.4
		'UPGRADE_WARNING: Couldn't resolve default property of object Rad(9). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Rad(9) = 31.5
		'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(1). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(1) = "! ID                                                                            "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(2). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(2) = "!   This initial data set was generated by the CARSTART program                 "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(3). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(3) = "!                                 |                                    ^        "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(4). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(4) = "  EE.000    ASy   Q.      .000   q.                                             "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(5). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(5) = "FREQ=vv.vv  DEEV=60.0  PHINIT=30.0  HA= 1.     LC                               "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(6). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(6) = "  33.870  35.070  vvvv.0  vvvv.0                                                "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(7). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(7) = "                                                                                "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(8). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(8) = "MAIN=   vvvv.0                                                                  "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(9). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(9) = "TRIM= 1   vvvv.00, 2   vvvv.00, 3   vvvv.00, 4   vvvv.00, 5   vvvv.00,          "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(10). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(10) = "      6  vvvv.00,  7  vvvv.00,  8  vvvv.00,F 9      .00,F10      .00,           "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(11). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(11) = "HAR=F OF1    25.00,  AM1     5.00,  PH1     5.00,                               "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(12). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(12) = "    F OF2      .00,F AM2      .00,F PH2      .00,                               "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(13). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(13) = "    F OF3      .00,F AM3      .00,F PH3      .00,                               "
		'UPGRADE_WARNING: Couldn't resolve default property of object C(14). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		C(14) = "    F OF4   320.00,  AM4    10.00,  PH4   100.00,                               "
		'
	End Sub
	
	Public Sub CarWrite()
		Dim I As Object
		'  writes card images to tcisoc.car file
		'UPGRADE_WARNING: Couldn't resolve default property of object filNam. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		FileOpen(1, filNam, OpenMode.Output)
		For I = 1 To 14
			'UPGRADE_WARNING: Couldn't resolve default property of object I. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			PrintLine(1, C(I))
		Next I
		FileClose(1)
	End Sub
	
	Public Sub Freq()
		'  calculates frequency for specified particle, energy, and orbit
		'UPGRADE_WARNING: Couldn't resolve default property of object Rflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Eflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Tflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Tflag = Eflag * Pflag * Rflag
		'UPGRADE_WARNING: Couldn't resolve default property of object Tflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		If Tflag > 0 Then
			'UPGRADE_WARNING: Couldn't resolve default property of object E. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			E = System.Math.Round(E)
			'UPGRADE_WARNING: Couldn't resolve default property of object dL. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object R. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object PartM. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object E. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object rf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			rf = 1878.486 * System.Math.Sqrt(1# - (PartM / (E + PartM)) ^ 2) / (R * dL)
			'UPGRADE_WARNING: Couldn't resolve default property of object rf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			rf = System.Math.Round(rf, 2)
			'UPGRADE_WARNING: Couldn't resolve default property of object rf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
            frmC.txtFreq.Text = rf
            ' Changed the RF limit from 19 to 24.  EjP 20230711
            If rf <= 24.01 Then
                frmC.txtFreq.BackColor = System.Drawing.ColorTranslator.FromOle(&HFFFFFF)
                frmC.cmdCalc.Enabled = True
            Else
                frmC.txtFreq.BackColor = System.Drawing.ColorTranslator.FromOle(&H8080FF)
            End If
			'UPGRADE_WARNING: Couldn't resolve default property of object R. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object partZ. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object partA. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object E. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			KB = (E * partA / partZ ^ 2) * (31# / R) ^ 2
			frmC.txtKB.Text = CStr(System.Math.Round(KB, 2))
			If KB < 45 Then
				frmC.txtKB.BackColor = System.Drawing.ColorTranslator.FromOle(&H8080FF)
				frmC.cmdCalc.Enabled = False
			Else
				If KB > 98 Then
					frmC.txtKB.BackColor = System.Drawing.ColorTranslator.FromOle(&H80FFFF)
				Else
					frmC.txtKB.BackColor = System.Drawing.ColorTranslator.FromOle(&HFFFFFF)
				End If
			End If
		Else
			frmC.txtFreq.Text = ""
			frmC.txtKB.Text = ""
		End If
	End Sub
	
	Public Sub PartPrm()
		If PartID = 0 Then
			'UPGRADE_WARNING: Couldn't resolve default property of object partA. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			partA = 1
			'UPGRADE_WARNING: Couldn't resolve default property of object partZ. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			partZ = 1
			'UPGRADE_WARNING: Couldn't resolve default property of object PartM. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			PartM = 938.255
			'UPGRADE_WARNING: Couldn't resolve default property of object C(4). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Mid(C(4), 13, 7) = "1H    1"
		End If
		If PartID = 1 Then
			'UPGRADE_WARNING: Couldn't resolve default property of object partA. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			partA = 2
			'UPGRADE_WARNING: Couldn't resolve default property of object partZ. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			partZ = 1
			'UPGRADE_WARNING: Couldn't resolve default property of object PartM. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			PartM = 1875.58
			'UPGRADE_WARNING: Couldn't resolve default property of object C(4). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Mid(C(4), 13, 7) = "2H    1"
		End If
		If PartID = 2 Then
			'UPGRADE_WARNING: Couldn't resolve default property of object partA. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			partA = 2
			'UPGRADE_WARNING: Couldn't resolve default property of object partZ. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			partZ = 1
			'UPGRADE_WARNING: Couldn't resolve default property of object PartM. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			PartM = 1877.02
			'UPGRADE_WARNING: Couldn't resolve default property of object C(4). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Mid(C(4), 13, 7) = "2HH   1"
		End If
		If PartID = 3 Then
			'UPGRADE_WARNING: Couldn't resolve default property of object partA. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			partA = 3
			'UPGRADE_WARNING: Couldn't resolve default property of object partZ. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			partZ = 2
			'UPGRADE_WARNING: Couldn't resolve default property of object PartM. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			PartM = 2808.34
			'UPGRADE_WARNING: Couldn't resolve default property of object C(4). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Mid(C(4), 13, 7) = "3He   2"
		End If
		If PartID = 4 Then
			'UPGRADE_WARNING: Couldn't resolve default property of object partA. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			partA = 4
			'UPGRADE_WARNING: Couldn't resolve default property of object partZ. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			partZ = 2
			'UPGRADE_WARNING: Couldn't resolve default property of object PartM. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			PartM = 3727.31
			'UPGRADE_WARNING: Couldn't resolve default property of object C(4). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Mid(C(4), 13, 7) = "4He   2"
		End If
	End Sub
	
	Public Sub CoilCur()
		Dim T8 As Object
		Dim T7 As Object
		Dim Cmain As Object
		'  calculates coil currents if CCflag=1, otherwise clears values
		'
		'UPGRADE_WARNING: Couldn't resolve default property of object CCflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		If CCflag = 1 Then
			'  calculate lower channel coil currents
			'UPGRADE_WARNING: Couldn't resolve default property of object R. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object partZ. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object partA. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object E. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			KB = (E * partA / partZ ^ 2) * (31# / R) ^ 2
			If KB <= 95 Then
				frmC.txtLCin.Text = CStr(System.Math.Round(43.333 * KB - 1116.7))
				frmC.txtLCout.Text = CStr(System.Math.Round(-9.333 * KB + 3006.7))
			Else
				frmC.txtLCin.Text = CStr(3000#)
				frmC.txtLCout.Text = CStr(System.Math.Round(22# * KB + 30#))
			End If
			'  estimate main field
			'UPGRADE_WARNING: Couldn't resolve default property of object Cmain. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Cmain = 0.33 * KB * KB + 10.2 * KB + 200
			'UPGRADE_WARNING: Couldn't resolve default property of object Cmain. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			frmC.txtMain.Text = CStr(System.Math.Round(Cmain))
			'UPGRADE_WARNING: Couldn't resolve default property of object Cmain. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			If Cmain > 4500 Then
				frmC.txtMain.BackColor = System.Drawing.ColorTranslator.FromOle(&H8080FF)
				frmC.cmdSave.Enabled = False
				'UPGRADE_WARNING: Couldn't resolve default property of object CCflag. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
				CCflag = 0
			Else
				frmC.txtMain.BackColor = System.Drawing.ColorTranslator.FromOle(&HFFFFFF)
				frmC.txtMain.Enabled = True
			End If
			'  estimate trim coils
			frmC.txtT1.Text = CStr(System.Math.Round(-0.6 * KB - 100))
			frmC.txtT2.Text = CStr(System.Math.Round(-5.2 * KB + 73))
			frmC.txtT3.Text = CStr(System.Math.Round(-6.4 * KB + 505))
			frmC.txtT4.Text = CStr(System.Math.Round(-5.8 * KB + 760))
			If CDbl(frmC.txtT4.Text) > 600 Then frmC.txtT4.Text = CStr(600)
			frmC.txtT5.Text = CStr(System.Math.Round(-7.7 * KB + 895))
			frmC.txtT6.Text = CStr(System.Math.Round(-6.6 * KB + 810))
			'UPGRADE_WARNING: Couldn't resolve default property of object T7. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			T7 = System.Math.Round(-5.7 * KB + 940)
			'UPGRADE_WARNING: Couldn't resolve default property of object T7. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			If System.Math.Abs(T7) > 650 Then
				'UPGRADE_WARNING: Couldn't resolve default property of object T7. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
				frmC.txtT7.Text = CStr(System.Math.Sign(T7) * 650)
				frmC.txtT7.BackColor = System.Drawing.ColorTranslator.FromOle(&H80FFFF)
			Else
				'UPGRADE_WARNING: Couldn't resolve default property of object T7. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
				frmC.txtT7.Text = CStr(System.Math.Round(T7))
				frmC.txtT7.BackColor = System.Drawing.ColorTranslator.FromOle(&HFFFFFF)
			End If
			'UPGRADE_WARNING: Couldn't resolve default property of object T8. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			T8 = System.Math.Round(-9.1 * KB + 915)
			'UPGRADE_WARNING: Couldn't resolve default property of object T8. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			If System.Math.Abs(T8) > 450 Then
				'UPGRADE_WARNING: Couldn't resolve default property of object T8. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
				frmC.txtT8.Text = CStr(System.Math.Sign(T8) * 450)
				frmC.txtT8.BackColor = System.Drawing.ColorTranslator.FromOle(&H80FFFF)
			Else
				'UPGRADE_WARNING: Couldn't resolve default property of object T8. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
				frmC.txtT8.Text = CStr(System.Math.Round(T8))
				frmC.txtT8.BackColor = System.Drawing.ColorTranslator.FromOle(&HFFFFFF)
			End If
			'  estimate Coax current
			frmC.txtCoax.Text = CStr(System.Math.Round(41.3 * KB + 1197))
			frmC.txtKB.Text = CStr(System.Math.Round(KB, 1))
			'
		Else 'clear all
			frmC.txtLCin.Text = ""
			frmC.txtLCout.Text = ""
			frmC.txtMain.Text = ""
			frmC.txtMain.BackColor = System.Drawing.ColorTranslator.FromOle(&HFFFFFF)
			frmC.txtT1.Text = ""
			frmC.txtT2.Text = ""
			frmC.txtT3.Text = ""
			frmC.txtT4.Text = ""
			frmC.txtT5.Text = ""
			frmC.txtT6.Text = ""
			frmC.txtT7.Text = ""
			frmC.txtT8.Text = ""
			frmC.txtCoax.Text = ""
			frmC.txtID.Text = ""
			frmC.cmdSave.Enabled = False
			frmC.lblFnam.Text = ""
			'UPGRADE_WARNING: Couldn't resolve default property of object C(1). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Mid(C(1), 43, 28) = "                            "
		End If
	End Sub
	
	Public Sub CarPrep()
		Dim LID As Object
		Dim Plen As Object
		'  function to extract values for calculated parameters and
		'  insert them into the card images
		'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pbuf = "   "
		'  first get parameters
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtE.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(4). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(4), 2, 3) = Right(Pbuf + Pval, 3)
		'UPGRADE_WARNING: Couldn't resolve default property of object partZ. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(4). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(4), 34, 1) = partZ
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtFreq.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(5). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(5), 6, 5) = Right(Pbuf + Pval, 5)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtLCin.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(6). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(6), 19, 4) = Right(Pbuf + Pval, 4)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtLCout.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(6). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(6), 27, 4) = Right(Pbuf + Pval, 4)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtMain.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(8). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(8), 8, 5) = Right(Pbuf + Pval, 5)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtT1.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(9). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(9), 11, 4) = Right(Pbuf + Pval, 4)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtT2.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(9). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(9), 24, 4) = Right(Pbuf + Pval, 4)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtT3.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(9). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(9), 37, 4) = Right(Pbuf + Pval, 4)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtT4.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(9). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(9), 50, 4) = Right(Pbuf + Pval, 4)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtT5.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(9). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(9), 63, 4) = Right(Pbuf + Pval, 4)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtT6.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(10). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(10), 10, 4) = Right(Pbuf + Pval, 4)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtT7.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(10). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(10), 23, 4) = Right(Pbuf + Pval, 4)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtT8.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(10). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(10), 36, 4) = Right(Pbuf + Pval, 4)
		'  now get parameter ID
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Pval = frmC.txtID.Text
		'UPGRADE_WARNING: Couldn't resolve default property of object Plen. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Plen = Len(Pval)
		'UPGRADE_WARNING: Couldn't resolve default property of object Pbuf. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object Plen. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object C(1). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Mid(C(1), 3, Plen + 3) = Pval + Pbuf 'enter ID on first comment card
		'  and construct output file name
		'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		'UPGRADE_WARNING: Couldn't resolve default property of object LID. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		LID = InStr(Pval + " ", " ") - 1 'make sure at least one blank
		'UPGRADE_WARNING: Couldn't resolve default property of object LID. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		If LID > 12 Then LID = 12 'limit file name to 12 characters
		'UPGRADE_WARNING: Couldn't resolve default property of object LID. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		If LID < 2 Then
			'UPGRADE_WARNING: Couldn't resolve default property of object filNam. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			filNam = "tcisoc.car"
		Else
			'UPGRADE_WARNING: Couldn't resolve default property of object LID. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object Pval. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object filNam. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			filNam = Left(Pval, LID) & ".tcisoc.car"
		End If
		'  write R and Coax to first comment card if requested
		If Xflag = 1 Then
			'UPGRADE_WARNING: Couldn't resolve default property of object R. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			SR = R
			'UPGRADE_WARNING: Couldn't resolve default property of object C(1). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Mid(C(1), 43, 15) = "Extract R ~" & SR & ".0" 'make sure are 15 characters
			'UPGRADE_WARNING: Couldn't resolve default property of object C(1). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Mid(C(1), 61, 10) = "COAX ~" & frmC.txtCoax.Text
		End If
		
		Debug.Print(C(1))
		Debug.Print(C(2))
		Debug.Print(C(3))
		Debug.Print(C(4))
		Debug.Print(C(5))
		Debug.Print(C(6))
		Debug.Print(C(7))
		Debug.Print(C(8))
		Debug.Print(C(9))
		Debug.Print(C(10))
		
	End Sub
End Module