SET PATH=C:\FORTRAN\BIN;C:\FORTRAN\BINB;C:\WINDOWS\;C:\windowS\COMMAND
SET LIB=C:\FORTRAN\LIB\
SET INCLUDE=C:\FORTRAN\INCLUDE\
SET HELPFILES=C:\FORTRAN\HELP\*.HLP
SET INIT=C:\FORTRAN\INIT\
SET TMP=c:\windows\TEMP

