Attribute VB_Name = "CARcode"
' JBCSTART Program
'   Generate best quess initial parameters for the tcisoc.car file
'
'   J. Ball    4-April-2007       Date of latest revision: 6/24/07
'
Public C(20), CaseID, Pval, Pbuf, filNam, SR As String
Public Eflag, Pflag, Rflag, Tflag, CCflag, PartID As Integer
Public IDflag, Xflag As Integer
Public PartM, partA, partZ, E, R, dL, Rad(9), rf, KB As Single

Public Sub Main()
  Eflag = 0
  Pflag = 0
  Rflag = 0
  CCflag = 0
  dL = 1#  'orbit stretch factor (actual path/pi*R^2)
'
  Rad(0) = 29#
  Rad(1) = 29.5
  Rad(2) = 30#
  Rad(3) = 30.5
  Rad(4) = 31#
  Rad(5) = 31.1
  Rad(6) = 31.2
  Rad(7) = 31.3
  Rad(8) = 31.4
  Rad(9) = 31.5
'
 C(1) = "! ID                                                                            "
 C(2) = "!   This initial data set was generated by the CARSTART program                 "
 C(3) = "!                                 |                                    ^        "
 C(4) = "  EE.000    ASy   Q.      .000   q.                                             "
 C(5) = "FREQ=vv.vv  DEEV=60.0  PHINIT=30.0  HA= 1.     LC                               "
 C(6) = "  33.870  35.070  vvvv.0  vvvv.0                                                "
 C(7) = "                                                                                "
 C(8) = "MAIN=   vvvv.0                                                                  "
 C(9) = "TRIM= 1   vvvv.00, 2   vvvv.00, 3   vvvv.00, 4   vvvv.00, 5   vvvv.00,          "
C(10) = "      6  vvvv.00,  7  vvvv.00,  8  vvvv.00,F 9      .00,F10      .00,           "
C(11) = "HAR=F OF1    25.00,  AM1     5.00,  PH1     5.00,                               "
C(12) = "    F OF2      .00,F AM2      .00,F PH2      .00,                               "
C(13) = "    F OF3      .00,F AM3      .00,F PH3      .00,                               "
C(14) = "    F OF4   320.00,  AM4    10.00,  PH4   100.00,                               "
'
End Sub

Public Sub CarWrite()
'  writes card images to tcisoc.car file
  Open filNam For Output As #1
  For I = 1 To 14
    Print #1, C(I)
  Next I
  Close #1
End Sub

Public Sub Freq()
'  calculates frequency for specified particle, energy, and orbit
  Tflag = Eflag * Pflag * Rflag
  If Tflag > 0 Then
    E = Round(E)
    rf = 1878.486 * Sqr(1# - (PartM / (E + PartM)) ^ 2) / (R * dL)
    rf = Round(rf, 2)
    frmC.txtFreq.Text = rf
    If rf <= 19.01 Then
      frmC.txtFreq.BackColor = &HFFFFFF
      frmC.cmdCalc.Enabled = True
    Else
      frmC.txtFreq.BackColor = &H8080FF
    End If
    KB = (E * partA / partZ ^ 2) * (31# / R) ^ 2
    frmC.txtKB.Text = Round(KB, 2)
    If KB < 45 Then
      frmC.txtKB.BackColor = &H8080FF
      frmC.cmdCalc.Enabled = False
    Else
      If KB > 98 Then
        frmC.txtKB.BackColor = &H80FFFF
      Else
        frmC.txtKB.BackColor = &HFFFFFF
      End If
    End If
  Else
    frmC.txtFreq = ""
    frmC.txtKB.Text = ""
  End If
End Sub

Public Sub PartPrm()
  If PartID = 0 Then
    partA = 1
    partZ = 1
    PartM = 938.255
    Mid(C(4), 13, 7) = "1H    1"
  End If
  If PartID = 1 Then
    partA = 2
    partZ = 1
    PartM = 1875.58
    Mid(C(4), 13, 7) = "2H    1"
  End If
  If PartID = 2 Then
    partA = 2
    partZ = 1
    PartM = 1877.02
    Mid(C(4), 13, 7) = "2HH   1"
  End If
  If PartID = 3 Then
    partA = 3
    partZ = 2
    PartM = 2808.34
    Mid(C(4), 13, 7) = "3He   2"
  End If
  If PartID = 4 Then
    partA = 4
    partZ = 2
    PartM = 3727.31
    Mid(C(4), 13, 7) = "4He   2"
  End If
End Sub

Public Sub CoilCur()
'  calculates coil currents if CCflag=1, otherwise clears values
'
  If CCflag = 1 Then
'  calculate lower channel coil currents
    KB = (E * partA / partZ ^ 2) * (31# / R) ^ 2
    If KB <= 95 Then
      frmC.txtLCin.Text = Round(43.333 * KB - 1116.7)
      frmC.txtLCout.Text = Round(-9.333 * KB + 3006.7)
    Else
      frmC.txtLCin.Text = 3000#
      frmC.txtLCout.Text = Round(22# * KB + 30#)
    End If
'  estimate main field
    Cmain = 0.33 * KB * KB + 10.2 * KB + 200
    frmC.txtMain = Round(Cmain)
    If Cmain > 4500 Then
      frmC.txtMain.BackColor = &H8080FF
      frmC.cmdSave.Enabled = False
      CCflag = 0
    Else
      frmC.txtMain.BackColor = &HFFFFFF
      frmC.txtMain.Enabled = True
    End If
'  estimate trim coils
    frmC.txtT1.Text = Round(-0.6 * KB - 100)
    frmC.txtT2.Text = Round(-5.2 * KB + 73)
    frmC.txtT3.Text = Round(-6.4 * KB + 505)
    frmC.txtT4.Text = Round(-5.8 * KB + 760)
    If frmC.txtT4.Text > 600 Then frmC.txtT4.Text = 600
    frmC.txtT5.Text = Round(-7.7 * KB + 895)
    frmC.txtT6.Text = Round(-6.6 * KB + 810)
    T7 = Round(-5.7 * KB + 940)
    If Abs(T7) > 650 Then
      frmC.txtT7 = Sgn(T7) * 650
      frmC.txtT7.BackColor = &H80FFFF
    Else
      frmC.txtT7.Text = Round(T7)
      frmC.txtT7.BackColor = &HFFFFFF
    End If
    T8 = Round(-9.1 * KB + 915)
    If Abs(T8) > 450 Then
      frmC.txtT8 = Sgn(T8) * 450
      frmC.txtT8.BackColor = &H80FFFF
    Else
      frmC.txtT8.Text = Round(T8)
      frmC.txtT8.BackColor = &HFFFFFF
    End If
'  estimate Coax current
    frmC.txtCoax.Text = Round(41.3 * KB + 1197)
    frmC.txtKB.Text = Round(KB, 1)
'
  Else                'clear all
    frmC.txtLCin.Text = ""
    frmC.txtLCout.Text = ""
    frmC.txtMain.Text = ""
    frmC.txtMain.BackColor = &HFFFFFF
    frmC.txtT1.Text = ""
    frmC.txtT2.Text = ""
    frmC.txtT3.Text = ""
    frmC.txtT4.Text = ""
    frmC.txtT5.Text = ""
    frmC.txtT6.Text = ""
    frmC.txtT7.Text = ""
    frmC.txtT8.Text = ""
    frmC.txtCoax.Text = ""
    frmC.txtID.Text = ""
    frmC.cmdSave.Enabled = False
    frmC.lblFnam.Caption = ""
    Mid(C(1), 43, 28) = "                            "
  End If
End Sub

Public Sub CarPrep()
'  function to extract values for calculated parameters and
'  insert them into the card images
'
  Pbuf = "   "
'  first get parameters
  Pval = frmC.txtE.Text
  Mid(C(4), 2, 3) = Right(Pbuf + Pval, 3)
  Mid(C(4), 34, 1) = partZ
  Pval = frmC.txtFreq.Text
  Mid(C(5), 6, 5) = Right(Pbuf + Pval, 5)
  Pval = frmC.txtLCin.Text
  Mid(C(6), 19, 4) = Right(Pbuf + Pval, 4)
  Pval = frmC.txtLCout.Text
  Mid(C(6), 27, 4) = Right(Pbuf + Pval, 4)
  Pval = frmC.txtMain.Text
  Mid(C(8), 8, 5) = Right(Pbuf + Pval, 5)
  Pval = frmC.txtT1.Text
  Mid(C(9), 11, 4) = Right(Pbuf + Pval, 4)
  Pval = frmC.txtT2.Text
  Mid(C(9), 24, 4) = Right(Pbuf + Pval, 4)
  Pval = frmC.txtT3.Text
  Mid(C(9), 37, 4) = Right(Pbuf + Pval, 4)
  Pval = frmC.txtT4.Text
  Mid(C(9), 50, 4) = Right(Pbuf + Pval, 4)
  Pval = frmC.txtT5.Text
  Mid(C(9), 63, 4) = Right(Pbuf + Pval, 4)
  Pval = frmC.txtT6.Text
  Mid(C(10), 10, 4) = Right(Pbuf + Pval, 4)
  Pval = frmC.txtT7.Text
  Mid(C(10), 23, 4) = Right(Pbuf + Pval, 4)
  Pval = frmC.txtT8.Text
  Mid(C(10), 36, 4) = Right(Pbuf + Pval, 4)
'  now get parameter ID
  Pval = frmC.txtID.Text
  Plen = Len(Pval)
  Mid(C(1), 3, Plen + 3) = Pval + Pbuf   'enter ID on first comment card
'  and construct output file name
  LID = InStr(Pval + " ", " ") - 1       'make sure at least one blank
  If LID > 12 Then LID = 12    'limit file name to 12 characters
  If LID < 2 Then
    filNam = "tcisoc.car"
  Else
    filNam = Left(Pval, LID) + ".tcisoc.car"
  End If
'  write R and Coax to first comment card if requested
  If Xflag = 1 Then
    SR = R
    Mid(C(1), 43, 15) = "Extract R ~" + SR + ".0"   'make sure are 15 characters
    Mid(C(1), 61, 10) = "COAX ~" + frmC.txtCoax.Text
  End If
  
  Debug.Print C(1)
  Debug.Print C(2)
  Debug.Print C(3)
  Debug.Print C(4)
  Debug.Print C(5)
  Debug.Print C(6)
  Debug.Print C(7)
  Debug.Print C(8)
  Debug.Print C(9)
  Debug.Print C(10)
  
End Sub
